### ISSUE TITLE
How can I contact you?

### ISSUE THREAD

**Issue by vbelevcev** [The-UnXplained/Menyoo#1]
How can I contact you? I need your help, I sincerely appreciate your work, unlike those who delete it, sorry for writing here, but I do not have time to contact you, then your mod delete, then you take offense and delete it yourself)) I support your error correction, during your last disappearance, began to understand menu and do something for myself, please contact me I really need your help to fix bugs
Discord sky_kotik
Telegram https://t.me/agaokda

**Comment by The-UnXplained** [comment]
What do you need help with.. ?

**Comment by vbelevcev** [comment]
need help with fixing options, such as character length I do for myself menu, your fixes are needed, the original is very unfinished, ideally need a connection with you

**Comment by The-UnXplained** [comment]
Player height is

`float GeneralGlobalHax::GetPlayerHeight()
{
	auto baddr = *GeneralGlobalHax::WorldPtrPtr();
	if (baddr)
	{
		auto gameVersion = GTAmemory::GetGameVersion();
		if (gameVersion <= eGameVersion::VER_1_0_2944_0)
			return *(GetMultilayerPointer<float*>(baddr, std::vector<DWORD>{0x8, 0x88}));
	}
	return 1.0f;
}
void GeneralGlobalHax::SetPlayerHeight(float value)
{
	auto baddr = *GeneralGlobalHax::WorldPtrPtr();
	if (baddr)
	{
		auto gameVersion = GTAmemory::GetGameVersion();
		if (gameVersion <= eGameVersion::VER_1_0_2944_0)
			*(GetMultilayerPointer<float*>(baddr, std::vector<DWORD>{0x8, 0x88})) = value;
	}
}`

You can find the rest yourself from the decompiled scripts, have fun :)

**Comment by vbelevcev** [comment]
Okay, thank you)) can you just give me the source code if you do not want to communicate?) you still have any fixes I will compare and then find it myself)

**Comment by vbelevcev** [comment]
put it in different places? not in the same code PlayerOptions.cpp? if I knew about the natives, I would not have asked for help) Although I have enough of your source code for comparison not to bother you

**Comment by The-UnXplained** [comment]
The above code is for GTAmemory.cpp - That has to be updated every game patch.

The original by mafins is very outdated, and has been messed about with by many people.

It takes time to learn c++ and alot of time looking in the decompiled scripts and finding things. 

I don't give out the updated source code to anyone, sorry..

If you really want to learn how to update it yourself, then i recommend you join https://www.unknowncheats.me/forum/grand-theft-auto-v/

or you can always find an up-to-date copy by me at www.gtamods4you.com - I am not going to disappear, i have been updating this menu for years! ps, you can upload a copy of it to your github page if you want. I don't mind.

**Comment by vbelevcev** [comment]
can you at least send it off?
Your site doesn't always work, I checked earlier it was offline for a few weeks

**Comment by The-UnXplained** [comment]
[Menyoo 05-07-2023.zip](https://github.com/The-UnXplained/Menyoo/files/11985170/Menyoo.05-07-2023.zip)

**Comment by vbelevcev** [comment]
I meant 
GTAmemory.cpp

**Comment by vbelevcev** [comment]
and on the github you delete both the account and the repository

**Comment by vbelevcev** [comment]
VER_1_0_2944_0
I can't compile because of this version of the game

**Comment by vbelevcev** [comment]
![image](https://github.com/The-UnXplained/Menyoo/assets/44013577/99fd64a9-28bb-4796-ac1c-0fd0f8153acf)

**Comment by vbelevcev** [comment]
not work

**Comment by vbelevcev** [comment]
I need working 3 options Character lengthening, running speed and swimming speed, they are all broken, if you do not want to help then write about it directly, and on these issues I asked for contacts,
You gave part of the code and it can not work because there is no support for the new version of the game as you have, I respect your work but no wonder that the developer with this approach fought with you, and that the menu is free and no one asks for money for it, I do for myself and am not going to share anything with anyone especially someone else, and for this there are private messages, not a forum
Your menu is also not perfect, and a lot of it is not., I add a little in my spare time, I would like to have one menu, but normal, but alas it will never be with this approach

**Comment by The-UnXplained** [comment]
Clearly you don't know what your doing.. 

#locked.

**Comment by The-UnXplained** [comment]
Clearly you don't know what your doing.. 

#locked.
